# 开发环境配置
spring:
  # 数据源配置(双数据源,单数据源的时候可以吧db2删除掉)
  datasource:
   db1: # 数据源1
    # mysql数据源配置例
    url: jdbc:mysql://localhost:3306/yuechuang?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false
    jdbc-url: ${spring.datasource.db1.url}
    username: root
    password:
#   db2: # 数据源2
#     # postgre数据源配置例
#     url: jdbc:postgresql://localhost:5432/gs
#     jdbc-url: ${spring.datasource.db2.url}
#     username: postgres
#     password: 123456
  jpa:
    #设置数据库方言
    #for mysql org.hibernate.dialect.MySQL5Dialect
    #for sqlserver org.hibernate.dialect.SQLServerDialect
    #for oracle org.hibernate.dialect.Oracle10gDialect
#    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: false #boolean类型,是否生成ddl
    hibernate:
      #自动更新enum
      #none: does nothing with the schema, makes no changes to the database
      #validate: validate the schema, makes no changes to the database.
      #update: update the schema.
      #create: creates the schema, destroying previous data.
      #create-drop: drop the schema when the SessionFactory is closed explicitly, typically when the application is stopped.
      ddl-auto: none
      format_sql: false
    show-sql: true  #日志中显示sql语句

wxpay:
  merchant-id: 1725430742
  merchant-serial-number: 551AF38CBF5B50E396334E47B6F2ED3AF9962034
  private-key-path: C:\Users\WZL\Desktop\code\悦创\1725430742_20250826_cert\keys\apiclient_key.pem
  api-v3-key: BeckhaM1981121119811211198112111
  app-id: wx17871fa309534443
  app-secret: 90b99ba25b760ed820ad5810c2c2d43f